main: me.bzBear.Bridge.Main
name: Bridge
version: V1
author: bzBear

softdepend: [HolographicDisplays]
commands:
  tb play:
  tb skip:
  tb leave:
  tb help:
  tb reset:
  tb score:
  tb leaderboards:
  tb: